# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectrometer_tabbed.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(901, 812)
        mainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTab.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(203, 240, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 240, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 240, 14))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.mainTab.setPalette(palette)
        self.mainTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.mainTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mainTab.setUsesScrollButtons(True)
        self.mainTab.setMovable(False)
        self.mainTab.setObjectName("mainTab")
        self.tab_sample = QtWidgets.QWidget()
        self.tab_sample.setObjectName("tab_sample")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_sample)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sampleMainFrame = QtWidgets.QFrame(self.tab_sample)
        self.sampleMainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.sampleMainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sampleMainFrame.setLineWidth(3)
        self.sampleMainFrame.setObjectName("sampleMainFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.sampleMainFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sampleTitleFrame = QtWidgets.QFrame(self.sampleMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleTitleFrame.sizePolicy().hasHeightForWidth())
        self.sampleTitleFrame.setSizePolicy(sizePolicy)
        self.sampleTitleFrame.setMinimumSize(QtCore.QSize(0, 62))
        self.sampleTitleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sampleTitleFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sampleTitleFrame.setLineWidth(3)
        self.sampleTitleFrame.setObjectName("sampleTitleFrame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.sampleTitleFrame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.sampleTitleLbl = QtWidgets.QLabel(self.sampleTitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleTitleLbl.sizePolicy().hasHeightForWidth())
        self.sampleTitleLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sampleTitleLbl.setFont(font)
        self.sampleTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleTitleLbl.setObjectName("sampleTitleLbl")
        self.gridLayout_11.addWidget(self.sampleTitleLbl, 0, 0, 1, 1)
        self.sampleTitleHLine = QtWidgets.QFrame(self.sampleTitleFrame)
        self.sampleTitleHLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sampleTitleHLine.setLineWidth(3)
        self.sampleTitleHLine.setMidLineWidth(1)
        self.sampleTitleHLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.sampleTitleHLine.setObjectName("sampleTitleHLine")
        self.gridLayout_11.addWidget(self.sampleTitleHLine, 1, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.sampleTitleFrame)
        self.sampleInfoFrame = QtWidgets.QFrame(self.sampleMainFrame)
        self.sampleInfoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sampleInfoFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sampleInfoFrame.setLineWidth(1)
        self.sampleInfoFrame.setObjectName("sampleInfoFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.sampleInfoFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sampleNameLineEdit = QtWidgets.QLineEdit(self.sampleInfoFrame)
        self.sampleNameLineEdit.setObjectName("sampleNameLineEdit")
        self.gridLayout_4.addWidget(self.sampleNameLineEdit, 0, 2, 1, 1)
        self.sampleNameLbl = QtWidgets.QLabel(self.sampleInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sampleNameLbl.setFont(font)
        self.sampleNameLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleNameLbl.setObjectName("sampleNameLbl")
        self.gridLayout_4.addWidget(self.sampleNameLbl, 0, 1, 1, 1)
        self.sampleMassLbl = QtWidgets.QLabel(self.sampleInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sampleMassLbl.setFont(font)
        self.sampleMassLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleMassLbl.setObjectName("sampleMassLbl")
        self.gridLayout_4.addWidget(self.sampleMassLbl, 1, 1, 1, 1)
        self.sampleMassLineEdit = QtWidgets.QLineEdit(self.sampleInfoFrame)
        self.sampleMassLineEdit.setObjectName("sampleMassLineEdit")
        self.gridLayout_4.addWidget(self.sampleMassLineEdit, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 3, 1, 1)
        self.verticalLayout_8.addWidget(self.sampleInfoFrame)
        self.currentSampleInfoFrame = QtWidgets.QFrame(self.sampleMainFrame)
        self.currentSampleInfoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentSampleInfoFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.currentSampleInfoFrame.setLineWidth(1)
        self.currentSampleInfoFrame.setObjectName("currentSampleInfoFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.currentSampleInfoFrame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.currentSampleNameLbl = QtWidgets.QLabel(self.currentSampleInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.currentSampleNameLbl.setFont(font)
        self.currentSampleNameLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.currentSampleNameLbl.setObjectName("currentSampleNameLbl")
        self.verticalLayout_10.addWidget(self.currentSampleNameLbl)
        self.currentSampleMassLbl = QtWidgets.QLabel(self.currentSampleInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.currentSampleMassLbl.setFont(font)
        self.currentSampleMassLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.currentSampleMassLbl.setObjectName("currentSampleMassLbl")
        self.verticalLayout_10.addWidget(self.currentSampleMassLbl)
        self.verticalLayout_8.addWidget(self.currentSampleInfoFrame)
        self.confirmSampleInfoFrame = QtWidgets.QFrame(self.sampleMainFrame)
        self.confirmSampleInfoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.confirmSampleInfoFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.confirmSampleInfoFrame.setObjectName("confirmSampleInfoFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.confirmSampleInfoFrame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.confirmSampleInfoBtn = QtWidgets.QPushButton(self.confirmSampleInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirmSampleInfoBtn.setFont(font)
        self.confirmSampleInfoBtn.setDefault(False)
        self.confirmSampleInfoBtn.setFlat(False)
        self.confirmSampleInfoBtn.setObjectName("confirmSampleInfoBtn")
        self.horizontalLayout_9.addWidget(self.confirmSampleInfoBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_8.addWidget(self.confirmSampleInfoFrame)
        self.bottomSampleFrame = QtWidgets.QFrame(self.sampleMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomSampleFrame.sizePolicy().hasHeightForWidth())
        self.bottomSampleFrame.setSizePolicy(sizePolicy)
        self.bottomSampleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomSampleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomSampleFrame.setObjectName("bottomSampleFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.bottomSampleFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.clearSampleInfoBtn = QtWidgets.QPushButton(self.bottomSampleFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearSampleInfoBtn.setFont(font)
        self.clearSampleInfoBtn.setObjectName("clearSampleInfoBtn")
        self.horizontalLayout_7.addWidget(self.clearSampleInfoBtn)
        spacerItem7 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.sampleTabNextBtn = QtWidgets.QPushButton(self.bottomSampleFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sampleTabNextBtn.setFont(font)
        self.sampleTabNextBtn.setObjectName("sampleTabNextBtn")
        self.horizontalLayout_7.addWidget(self.sampleTabNextBtn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_8.addWidget(self.bottomSampleFrame)
        self.verticalLayout_3.addWidget(self.sampleMainFrame)
        self.mainTab.addTab(self.tab_sample, "")
        self.tab_seq = QtWidgets.QWidget()
        self.tab_seq.setObjectName("tab_seq")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_seq)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sequenceMainFrame = QtWidgets.QFrame(self.tab_seq)
        self.sequenceMainFrame.setAutoFillBackground(False)
        self.sequenceMainFrame.setStyleSheet("")
        self.sequenceMainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.sequenceMainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sequenceMainFrame.setLineWidth(3)
        self.sequenceMainFrame.setObjectName("sequenceMainFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.sequenceMainFrame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.sequenceTitleFrame = QtWidgets.QFrame(self.sequenceMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceTitleFrame.sizePolicy().hasHeightForWidth())
        self.sequenceTitleFrame.setSizePolicy(sizePolicy)
        self.sequenceTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sequenceTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sequenceTitleFrame.setObjectName("sequenceTitleFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.sequenceTitleFrame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.sequenceTitleLbl = QtWidgets.QLabel(self.sequenceTitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceTitleLbl.sizePolicy().hasHeightForWidth())
        self.sequenceTitleLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sequenceTitleLbl.setFont(font)
        self.sequenceTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sequenceTitleLbl.setObjectName("sequenceTitleLbl")
        self.verticalLayout_11.addWidget(self.sequenceTitleLbl)
        self.sequenceHLine = QtWidgets.QFrame(self.sequenceTitleFrame)
        self.sequenceHLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sequenceHLine.setLineWidth(3)
        self.sequenceHLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.sequenceHLine.setObjectName("sequenceHLine")
        self.verticalLayout_11.addWidget(self.sequenceHLine)
        self.verticalLayout_14.addWidget(self.sequenceTitleFrame)
        self.sequenceSubFrame = QtWidgets.QFrame(self.sequenceMainFrame)
        self.sequenceSubFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sequenceSubFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sequenceSubFrame.setObjectName("sequenceSubFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.sequenceSubFrame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.createSequenceFrame = QtWidgets.QFrame(self.sequenceSubFrame)
        self.createSequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createSequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createSequenceFrame.setObjectName("createSequenceFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.createSequenceFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.createSeqLbl = QtWidgets.QLabel(self.createSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createSeqLbl.sizePolicy().hasHeightForWidth())
        self.createSeqLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.createSeqLbl.setFont(font)
        self.createSeqLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.createSeqLbl.setObjectName("createSeqLbl")
        self.verticalLayout_12.addWidget(self.createSeqLbl)
        self.createSequenceLineEditFrame = QtWidgets.QFrame(self.createSequenceFrame)
        self.createSequenceLineEditFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createSequenceLineEditFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createSequenceLineEditFrame.setObjectName("createSequenceLineEditFrame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.createSequenceLineEditFrame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frequencyLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequencyLbl.sizePolicy().hasHeightForWidth())
        self.frequencyLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frequencyLbl.setFont(font)
        self.frequencyLbl.setObjectName("frequencyLbl")
        self.gridLayout_12.addWidget(self.frequencyLbl, 0, 0, 1, 1)
        self.pulse2LenLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse2LenLineEdit.sizePolicy().hasHeightForWidth())
        self.pulse2LenLineEdit.setSizePolicy(sizePolicy)
        self.pulse2LenLineEdit.setObjectName("pulse2LenLineEdit")
        self.gridLayout_12.addWidget(self.pulse2LenLineEdit, 3, 1, 1, 1)
        self.gapLenLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gapLenLbl.sizePolicy().hasHeightForWidth())
        self.gapLenLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gapLenLbl.setFont(font)
        self.gapLenLbl.setObjectName("gapLenLbl")
        self.gridLayout_12.addWidget(self.gapLenLbl, 4, 0, 1, 1)
        self.gapLenLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gapLenLineEdit.sizePolicy().hasHeightForWidth())
        self.gapLenLineEdit.setSizePolicy(sizePolicy)
        self.gapLenLineEdit.setObjectName("gapLenLineEdit")
        self.gridLayout_12.addWidget(self.gapLenLineEdit, 4, 1, 1, 1)
        self.phaseLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseLbl.sizePolicy().hasHeightForWidth())
        self.phaseLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phaseLbl.setFont(font)
        self.phaseLbl.setObjectName("phaseLbl")
        self.gridLayout_12.addWidget(self.phaseLbl, 1, 0, 1, 1)
        self.pulse1LenLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse1LenLbl.sizePolicy().hasHeightForWidth())
        self.pulse1LenLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pulse1LenLbl.setFont(font)
        self.pulse1LenLbl.setObjectName("pulse1LenLbl")
        self.gridLayout_12.addWidget(self.pulse1LenLbl, 2, 0, 1, 1)
        self.pulse1LenLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse1LenLineEdit.sizePolicy().hasHeightForWidth())
        self.pulse1LenLineEdit.setSizePolicy(sizePolicy)
        self.pulse1LenLineEdit.setObjectName("pulse1LenLineEdit")
        self.gridLayout_12.addWidget(self.pulse1LenLineEdit, 2, 1, 1, 1)
        self.frequencyLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequencyLineEdit.sizePolicy().hasHeightForWidth())
        self.frequencyLineEdit.setSizePolicy(sizePolicy)
        self.frequencyLineEdit.setObjectName("frequencyLineEdit")
        self.gridLayout_12.addWidget(self.frequencyLineEdit, 0, 1, 1, 1)
        self.pulse2LenLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse2LenLbl.sizePolicy().hasHeightForWidth())
        self.pulse2LenLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pulse2LenLbl.setFont(font)
        self.pulse2LenLbl.setObjectName("pulse2LenLbl")
        self.gridLayout_12.addWidget(self.pulse2LenLbl, 3, 0, 1, 1)
        self.recLenLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recLenLbl.sizePolicy().hasHeightForWidth())
        self.recLenLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.recLenLbl.setFont(font)
        self.recLenLbl.setObjectName("recLenLbl")
        self.gridLayout_12.addWidget(self.recLenLbl, 5, 0, 1, 1)
        self.recLenLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recLenLineEdit.sizePolicy().hasHeightForWidth())
        self.recLenLineEdit.setSizePolicy(sizePolicy)
        self.recLenLineEdit.setObjectName("recLenLineEdit")
        self.gridLayout_12.addWidget(self.recLenLineEdit, 5, 1, 1, 1)
        self.phaseComboBox = QtWidgets.QComboBox(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseComboBox.sizePolicy().hasHeightForWidth())
        self.phaseComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phaseComboBox.setFont(font)
        self.phaseComboBox.setFrame(True)
        self.phaseComboBox.setObjectName("phaseComboBox")
        self.phaseComboBox.addItem("")
        self.phaseComboBox.addItem("")
        self.phaseComboBox.addItem("")
        self.phaseComboBox.addItem("")
        self.gridLayout_12.addWidget(self.phaseComboBox, 1, 1, 1, 1)
        self.clearAllBtn = QtWidgets.QPushButton(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearAllBtn.sizePolicy().hasHeightForWidth())
        self.clearAllBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearAllBtn.setFont(font)
        self.clearAllBtn.setObjectName("clearAllBtn")
        self.gridLayout_12.addWidget(self.clearAllBtn, 6, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.createSequenceLineEditFrame)
        self.horizontalLayout_8.addWidget(self.createSequenceFrame)
        self.loadAndSaveSequenceFrame = QtWidgets.QFrame(self.sequenceSubFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadAndSaveSequenceFrame.sizePolicy().hasHeightForWidth())
        self.loadAndSaveSequenceFrame.setSizePolicy(sizePolicy)
        self.loadAndSaveSequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadAndSaveSequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadAndSaveSequenceFrame.setObjectName("loadAndSaveSequenceFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.loadAndSaveSequenceFrame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.loadSeqTitleLbl = QtWidgets.QLabel(self.loadAndSaveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSeqTitleLbl.sizePolicy().hasHeightForWidth())
        self.loadSeqTitleLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.loadSeqTitleLbl.setFont(font)
        self.loadSeqTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.loadSeqTitleLbl.setObjectName("loadSeqTitleLbl")
        self.verticalLayout_13.addWidget(self.loadSeqTitleLbl)
        self.loadSequenceFrame = QtWidgets.QFrame(self.loadAndSaveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSequenceFrame.sizePolicy().hasHeightForWidth())
        self.loadSequenceFrame.setSizePolicy(sizePolicy)
        self.loadSequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadSequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadSequenceFrame.setObjectName("loadSequenceFrame")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.loadSequenceFrame)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.loadSeqBtn = QtWidgets.QPushButton(self.loadSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSeqBtn.sizePolicy().hasHeightForWidth())
        self.loadSeqBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadSeqBtn.setFont(font)
        self.loadSeqBtn.setObjectName("loadSeqBtn")
        self.gridLayout_17.addWidget(self.loadSeqBtn, 2, 1, 1, 1)
        self.loadedSeqLbl = QtWidgets.QLabel(self.loadSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadedSeqLbl.sizePolicy().hasHeightForWidth())
        self.loadedSeqLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadedSeqLbl.setFont(font)
        self.loadedSeqLbl.setObjectName("loadedSeqLbl")
        self.gridLayout_17.addWidget(self.loadedSeqLbl, 0, 0, 1, 1)
        self.loadedSeqLineEdit = QtWidgets.QLineEdit(self.loadSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadedSeqLineEdit.sizePolicy().hasHeightForWidth())
        self.loadedSeqLineEdit.setSizePolicy(sizePolicy)
        self.loadedSeqLineEdit.setText("")
        self.loadedSeqLineEdit.setReadOnly(True)
        self.loadedSeqLineEdit.setObjectName("loadedSeqLineEdit")
        self.gridLayout_17.addWidget(self.loadedSeqLineEdit, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem9, 1, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.loadSequenceFrame)
        self.saveSeqTitleLbl = QtWidgets.QLabel(self.loadAndSaveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSeqTitleLbl.sizePolicy().hasHeightForWidth())
        self.saveSeqTitleLbl.setSizePolicy(sizePolicy)
        self.saveSeqTitleLbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.saveSeqTitleLbl.setFont(font)
        self.saveSeqTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.saveSeqTitleLbl.setObjectName("saveSeqTitleLbl")
        self.verticalLayout_13.addWidget(self.saveSeqTitleLbl)
        self.saveSequenceFrame = QtWidgets.QFrame(self.loadAndSaveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSequenceFrame.sizePolicy().hasHeightForWidth())
        self.saveSequenceFrame.setSizePolicy(sizePolicy)
        self.saveSequenceFrame.setMinimumSize(QtCore.QSize(0, 177))
        self.saveSequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveSequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saveSequenceFrame.setObjectName("saveSequenceFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.saveSequenceFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.savedSeqLbl = QtWidgets.QLabel(self.saveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedSeqLbl.sizePolicy().hasHeightForWidth())
        self.savedSeqLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.savedSeqLbl.setFont(font)
        self.savedSeqLbl.setObjectName("savedSeqLbl")
        self.gridLayout_5.addWidget(self.savedSeqLbl, 0, 0, 1, 1)
        self.savedSeqLineEdit = QtWidgets.QLineEdit(self.saveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedSeqLineEdit.sizePolicy().hasHeightForWidth())
        self.savedSeqLineEdit.setSizePolicy(sizePolicy)
        self.savedSeqLineEdit.setReadOnly(True)
        self.savedSeqLineEdit.setObjectName("savedSeqLineEdit")
        self.gridLayout_5.addWidget(self.savedSeqLineEdit, 0, 1, 1, 1)
        self.saveSeqBtn = QtWidgets.QPushButton(self.saveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSeqBtn.sizePolicy().hasHeightForWidth())
        self.saveSeqBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveSeqBtn.setFont(font)
        self.saveSeqBtn.setObjectName("saveSeqBtn")
        self.gridLayout_5.addWidget(self.saveSeqBtn, 1, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.saveSequenceFrame)
        self.horizontalLayout_8.addWidget(self.loadAndSaveSequenceFrame)
        self.verticalLayout_14.addWidget(self.sequenceSubFrame)
        self.verticalLayout_9.addWidget(self.sequenceMainFrame)
        self.mainTab.addTab(self.tab_seq, "")
        self.tab_expt = QtWidgets.QWidget()
        self.tab_expt.setObjectName("tab_expt")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_expt)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.exptMainFrame = QtWidgets.QFrame(self.tab_expt)
        self.exptMainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.exptMainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.exptMainFrame.setLineWidth(3)
        self.exptMainFrame.setObjectName("exptMainFrame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.exptMainFrame)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.exptTitleFrame = QtWidgets.QFrame(self.exptMainFrame)
        self.exptTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exptTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exptTitleFrame.setObjectName("exptTitleFrame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.exptTitleFrame)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.exptTitleLbl = QtWidgets.QLabel(self.exptTitleFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.exptTitleLbl.setFont(font)
        self.exptTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.exptTitleLbl.setObjectName("exptTitleLbl")
        self.verticalLayout_17.addWidget(self.exptTitleLbl)
        self.exptTitleHLine = QtWidgets.QFrame(self.exptTitleFrame)
        self.exptTitleHLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.exptTitleHLine.setLineWidth(3)
        self.exptTitleHLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.exptTitleHLine.setObjectName("exptTitleHLine")
        self.verticalLayout_17.addWidget(self.exptTitleHLine)
        self.verticalLayout_16.addWidget(self.exptTitleFrame)
        self.exptTreeWidget = QtWidgets.QTreeWidget(self.exptMainFrame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.exptTreeWidget.setFont(font)
        self.exptTreeWidget.setObjectName("exptTreeWidget")
        self.verticalLayout_16.addWidget(self.exptTreeWidget)
        self.addRemoveBtnFrame = QtWidgets.QFrame(self.exptMainFrame)
        self.addRemoveBtnFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.addRemoveBtnFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.addRemoveBtnFrame.setLineWidth(2)
        self.addRemoveBtnFrame.setObjectName("addRemoveBtnFrame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.addRemoveBtnFrame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.addSeqBtn = QtWidgets.QPushButton(self.addRemoveBtnFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addSeqBtn.setFont(font)
        self.addSeqBtn.setObjectName("addSeqBtn")
        self.gridLayout_10.addWidget(self.addSeqBtn, 0, 0, 1, 1)
        self.editSeqBtn = QtWidgets.QPushButton(self.addRemoveBtnFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editSeqBtn.setFont(font)
        self.editSeqBtn.setObjectName("editSeqBtn")
        self.gridLayout_10.addWidget(self.editSeqBtn, 1, 0, 1, 1)
        self.removeSeqBtn = QtWidgets.QPushButton(self.addRemoveBtnFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeSeqBtn.setFont(font)
        self.removeSeqBtn.setObjectName("removeSeqBtn")
        self.gridLayout_10.addWidget(self.removeSeqBtn, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.addRemoveBtnFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_10.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.verticalLayout_16.addWidget(self.addRemoveBtnFrame)
        self.exptTextEdit = QtWidgets.QTextEdit(self.exptMainFrame)
        self.exptTextEdit.setObjectName("exptTextEdit")
        self.verticalLayout_16.addWidget(self.exptTextEdit)
        self.verticalLayout_15.addWidget(self.exptMainFrame)
        self.mainTab.addTab(self.tab_expt, "")
        self.tab_run = QtWidgets.QWidget()
        self.tab_run.setObjectName("tab_run")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_run)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.runExptFrame = QtWidgets.QFrame(self.tab_run)
        self.runExptFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.runExptFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.runExptFrame.setLineWidth(3)
        self.runExptFrame.setObjectName("runExptFrame")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.runExptFrame)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.runTitleFrame = QtWidgets.QFrame(self.runExptFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runTitleFrame.sizePolicy().hasHeightForWidth())
        self.runTitleFrame.setSizePolicy(sizePolicy)
        self.runTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.runTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.runTitleFrame.setObjectName("runTitleFrame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.runTitleFrame)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label = QtWidgets.QLabel(self.runTitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_18.addWidget(self.label)
        self.line_6 = QtWidgets.QFrame(self.runTitleFrame)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_18.addWidget(self.line_6)
        self.verticalLayout_23.addWidget(self.runTitleFrame)
        self.runMainFrame = QtWidgets.QFrame(self.runExptFrame)
        self.runMainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.runMainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.runMainFrame.setObjectName("runMainFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.runMainFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.runInfoFrame = QtWidgets.QFrame(self.runMainFrame)
        self.runInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.runInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.runInfoFrame.setObjectName("runInfoFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.runInfoFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.runExptBtn = QtWidgets.QPushButton(self.runInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.runExptBtn.setFont(font)
        self.runExptBtn.setObjectName("runExptBtn")
        self.verticalLayout.addWidget(self.runExptBtn)
        self.currentSeqLbl = QtWidgets.QLabel(self.runInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentSeqLbl.sizePolicy().hasHeightForWidth())
        self.currentSeqLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currentSeqLbl.setFont(font)
        self.currentSeqLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.currentSeqLbl.setObjectName("currentSeqLbl")
        self.verticalLayout.addWidget(self.currentSeqLbl)
        self.currentRepeatLbl = QtWidgets.QLabel(self.runInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentRepeatLbl.sizePolicy().hasHeightForWidth())
        self.currentRepeatLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currentRepeatLbl.setFont(font)
        self.currentRepeatLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.currentRepeatLbl.setObjectName("currentRepeatLbl")
        self.verticalLayout.addWidget(self.currentRepeatLbl)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_3.addWidget(self.runInfoFrame)
        self.exptPlotTabWidget = QtWidgets.QTabWidget(self.runMainFrame)
        self.exptPlotTabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.exptPlotTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.exptPlotTabWidget.setObjectName("exptPlotTabWidget")
        self.tab_liveNMR = QtWidgets.QWidget()
        self.tab_liveNMR.setObjectName("tab_liveNMR")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_liveNMR)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.liveNMRPlotWidget = MplWidget(self.tab_liveNMR)
        self.liveNMRPlotWidget.setObjectName("liveNMRPlotWidget")
        self.horizontalLayout.addWidget(self.liveNMRPlotWidget)
        self.exptPlotTabWidget.addTab(self.tab_liveNMR, "")
        self.tab_livePPMS = QtWidgets.QWidget()
        self.tab_livePPMS.setObjectName("tab_livePPMS")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_livePPMS)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.livePPMSPlotWidget = MplWidget(self.tab_livePPMS)
        self.livePPMSPlotWidget.setObjectName("livePPMSPlotWidget")
        self.verticalLayout_19.addWidget(self.livePPMSPlotWidget)
        self.exptPlotTabWidget.addTab(self.tab_livePPMS, "")
        self.horizontalLayout_3.addWidget(self.exptPlotTabWidget)
        self.verticalLayout_23.addWidget(self.runMainFrame)
        self.gridLayout_8.addWidget(self.runExptFrame, 0, 0, 1, 1)
        self.mainTab.addTab(self.tab_run, "")
        self.tab_PPMS = QtWidgets.QWidget()
        self.tab_PPMS.setObjectName("tab_PPMS")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_PPMS)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.PPMSMainFrame = QtWidgets.QFrame(self.tab_PPMS)
        self.PPMSMainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.PPMSMainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PPMSMainFrame.setLineWidth(3)
        self.PPMSMainFrame.setObjectName("PPMSMainFrame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.PPMSMainFrame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_29 = QtWidgets.QFrame(self.PPMSMainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_29.sizePolicy().hasHeightForWidth())
        self.frame_29.setSizePolicy(sizePolicy)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_2 = QtWidgets.QLabel(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_21.addWidget(self.label_2)
        self.line_7 = QtWidgets.QFrame(self.frame_29)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_21.addWidget(self.line_7)
        self.verticalLayout_20.addWidget(self.frame_29)
        self.PPMSInfoFrame = QtWidgets.QFrame(self.PPMSMainFrame)
        self.PPMSInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PPMSInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PPMSInfoFrame.setObjectName("PPMSInfoFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.PPMSInfoFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.setTempFrame = QtWidgets.QFrame(self.PPMSInfoFrame)
        self.setTempFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.setTempFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.setTempFrame.setLineWidth(3)
        self.setTempFrame.setObjectName("setTempFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.setTempFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tempInfoFrame = QtWidgets.QFrame(self.setTempFrame)
        self.tempInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tempInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tempInfoFrame.setObjectName("tempInfoFrame")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tempInfoFrame)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.TempValDescLbl = QtWidgets.QLabel(self.tempInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TempValDescLbl.sizePolicy().hasHeightForWidth())
        self.TempValDescLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TempValDescLbl.setFont(font)
        self.TempValDescLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TempValDescLbl.setObjectName("TempValDescLbl")
        self.gridLayout_14.addWidget(self.TempValDescLbl, 0, 0, 1, 1)
        self.TempValLbl = QtWidgets.QLabel(self.tempInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TempValLbl.sizePolicy().hasHeightForWidth())
        self.TempValLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TempValLbl.setFont(font)
        self.TempValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TempValLbl.setObjectName("TempValLbl")
        self.gridLayout_14.addWidget(self.TempValLbl, 0, 1, 1, 1)
        self.TempStateDescLbl = QtWidgets.QLabel(self.tempInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TempStateDescLbl.sizePolicy().hasHeightForWidth())
        self.TempStateDescLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TempStateDescLbl.setFont(font)
        self.TempStateDescLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TempStateDescLbl.setObjectName("TempStateDescLbl")
        self.gridLayout_14.addWidget(self.TempStateDescLbl, 1, 0, 1, 1)
        self.TempStateLbl = QtWidgets.QLabel(self.tempInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TempStateLbl.sizePolicy().hasHeightForWidth())
        self.TempStateLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TempStateLbl.setFont(font)
        self.TempStateLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.TempStateLbl.setObjectName("TempStateLbl")
        self.gridLayout_14.addWidget(self.TempStateLbl, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.tempInfoFrame)
        self.tempControlFrame = QtWidgets.QFrame(self.setTempFrame)
        self.tempControlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tempControlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tempControlFrame.setObjectName("tempControlFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tempControlFrame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.SetTempLineEdit = QtWidgets.QLineEdit(self.tempControlFrame)
        self.SetTempLineEdit.setObjectName("SetTempLineEdit")
        self.horizontalLayout_10.addWidget(self.SetTempLineEdit)
        self.SetTempBtn = QtWidgets.QPushButton(self.tempControlFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SetTempBtn.setFont(font)
        self.SetTempBtn.setObjectName("SetTempBtn")
        self.horizontalLayout_10.addWidget(self.SetTempBtn)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.verticalLayout_5.addWidget(self.tempControlFrame)
        self.gridLayout_3.addWidget(self.setTempFrame, 0, 0, 1, 1)
        self.SetFieldFrame = QtWidgets.QFrame(self.PPMSInfoFrame)
        self.SetFieldFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.SetFieldFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SetFieldFrame.setLineWidth(3)
        self.SetFieldFrame.setObjectName("SetFieldFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.SetFieldFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fieldInfoFrame = QtWidgets.QFrame(self.SetFieldFrame)
        self.fieldInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fieldInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fieldInfoFrame.setObjectName("fieldInfoFrame")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.fieldInfoFrame)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.FieldValDesclbl = QtWidgets.QLabel(self.fieldInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FieldValDesclbl.sizePolicy().hasHeightForWidth())
        self.FieldValDesclbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FieldValDesclbl.setFont(font)
        self.FieldValDesclbl.setAlignment(QtCore.Qt.AlignCenter)
        self.FieldValDesclbl.setObjectName("FieldValDesclbl")
        self.gridLayout_15.addWidget(self.FieldValDesclbl, 0, 0, 1, 1)
        self.FieldValLbl = QtWidgets.QLabel(self.fieldInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FieldValLbl.sizePolicy().hasHeightForWidth())
        self.FieldValLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FieldValLbl.setFont(font)
        self.FieldValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.FieldValLbl.setObjectName("FieldValLbl")
        self.gridLayout_15.addWidget(self.FieldValLbl, 0, 1, 1, 1)
        self.FieldStateLbl = QtWidgets.QLabel(self.fieldInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FieldStateLbl.sizePolicy().hasHeightForWidth())
        self.FieldStateLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FieldStateLbl.setFont(font)
        self.FieldStateLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.FieldStateLbl.setObjectName("FieldStateLbl")
        self.gridLayout_15.addWidget(self.FieldStateLbl, 1, 1, 1, 1)
        self.FieldStateDescLbl = QtWidgets.QLabel(self.fieldInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FieldStateDescLbl.sizePolicy().hasHeightForWidth())
        self.FieldStateDescLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FieldStateDescLbl.setFont(font)
        self.FieldStateDescLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.FieldStateDescLbl.setObjectName("FieldStateDescLbl")
        self.gridLayout_15.addWidget(self.FieldStateDescLbl, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.fieldInfoFrame)
        self.fieldControlFrame = QtWidgets.QFrame(self.SetFieldFrame)
        self.fieldControlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fieldControlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fieldControlFrame.setObjectName("fieldControlFrame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.fieldControlFrame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.SetFieldLineEdit = QtWidgets.QLineEdit(self.fieldControlFrame)
        self.SetFieldLineEdit.setObjectName("SetFieldLineEdit")
        self.horizontalLayout_11.addWidget(self.SetFieldLineEdit)
        self.SetFieldBtn = QtWidgets.QPushButton(self.fieldControlFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SetFieldBtn.setFont(font)
        self.SetFieldBtn.setObjectName("SetFieldBtn")
        self.horizontalLayout_11.addWidget(self.SetFieldBtn)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_6.addWidget(self.fieldControlFrame)
        self.gridLayout_3.addWidget(self.SetFieldFrame, 0, 1, 1, 1)
        self.chamberFrame = QtWidgets.QFrame(self.PPMSInfoFrame)
        self.chamberFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.chamberFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.chamberFrame.setLineWidth(3)
        self.chamberFrame.setObjectName("chamberFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.chamberFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.chamberInfoFrame = QtWidgets.QFrame(self.chamberFrame)
        self.chamberInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chamberInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chamberInfoFrame.setObjectName("chamberInfoFrame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.chamberInfoFrame)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.LevelValLbl = QtWidgets.QLabel(self.chamberInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevelValLbl.sizePolicy().hasHeightForWidth())
        self.LevelValLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LevelValLbl.setFont(font)
        self.LevelValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.LevelValLbl.setObjectName("LevelValLbl")
        self.gridLayout_16.addWidget(self.LevelValLbl, 1, 1, 1, 1)
        self.LevelValDescLbl = QtWidgets.QLabel(self.chamberInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LevelValDescLbl.sizePolicy().hasHeightForWidth())
        self.LevelValDescLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LevelValDescLbl.setFont(font)
        self.LevelValDescLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.LevelValDescLbl.setObjectName("LevelValDescLbl")
        self.gridLayout_16.addWidget(self.LevelValDescLbl, 1, 0, 1, 1)
        self.chamberStatusDescLbl = QtWidgets.QLabel(self.chamberInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chamberStatusDescLbl.sizePolicy().hasHeightForWidth())
        self.chamberStatusDescLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chamberStatusDescLbl.setFont(font)
        self.chamberStatusDescLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.chamberStatusDescLbl.setObjectName("chamberStatusDescLbl")
        self.gridLayout_16.addWidget(self.chamberStatusDescLbl, 0, 0, 1, 1)
        self.chamberStatusLbl = QtWidgets.QLabel(self.chamberInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chamberStatusLbl.sizePolicy().hasHeightForWidth())
        self.chamberStatusLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chamberStatusLbl.setFont(font)
        self.chamberStatusLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.chamberStatusLbl.setObjectName("chamberStatusLbl")
        self.gridLayout_16.addWidget(self.chamberStatusLbl, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.chamberInfoFrame)
        self.gridLayout_3.addWidget(self.chamberFrame, 1, 0, 1, 1)
        self.updateBtnFrame = QtWidgets.QFrame(self.PPMSInfoFrame)
        self.updateBtnFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.updateBtnFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.updateBtnFrame.setLineWidth(3)
        self.updateBtnFrame.setObjectName("updateBtnFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.updateBtnFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.updatePPMSFrame = QtWidgets.QFrame(self.updateBtnFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updatePPMSFrame.sizePolicy().hasHeightForWidth())
        self.updatePPMSFrame.setSizePolicy(sizePolicy)
        self.updatePPMSFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.updatePPMSFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.updatePPMSFrame.setObjectName("updatePPMSFrame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.updatePPMSFrame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.PPMSAutoUpdateBtn = QtWidgets.QCheckBox(self.updatePPMSFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PPMSAutoUpdateBtn.setFont(font)
        self.PPMSAutoUpdateBtn.setObjectName("PPMSAutoUpdateBtn")
        self.gridLayout_18.addWidget(self.PPMSAutoUpdateBtn, 2, 0, 1, 1)
        self.PPMSUpdateBtn = QtWidgets.QPushButton(self.updatePPMSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PPMSUpdateBtn.sizePolicy().hasHeightForWidth())
        self.PPMSUpdateBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PPMSUpdateBtn.setFont(font)
        self.PPMSUpdateBtn.setObjectName("PPMSUpdateBtn")
        self.gridLayout_18.addWidget(self.PPMSUpdateBtn, 1, 0, 1, 1)
        self.PPMSConnectBtn = QtWidgets.QPushButton(self.updatePPMSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PPMSConnectBtn.sizePolicy().hasHeightForWidth())
        self.PPMSConnectBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PPMSConnectBtn.setFont(font)
        self.PPMSConnectBtn.setObjectName("PPMSConnectBtn")
        self.gridLayout_18.addWidget(self.PPMSConnectBtn, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.updatePPMSFrame)
        self.gridLayout_3.addWidget(self.updateBtnFrame, 1, 1, 1, 1)
        self.verticalLayout_20.addWidget(self.PPMSInfoFrame)
        self.verticalLayout_22.addWidget(self.PPMSMainFrame)
        self.mainTab.addTab(self.tab_PPMS, "")
        self.tab_debug = QtWidgets.QWidget()
        self.tab_debug.setObjectName("tab_debug")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_debug)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.function1Btn = QtWidgets.QPushButton(self.tab_debug)
        self.function1Btn.setObjectName("function1Btn")
        self.verticalLayout_2.addWidget(self.function1Btn)
        self.function2Btn = QtWidgets.QPushButton(self.tab_debug)
        self.function2Btn.setObjectName("function2Btn")
        self.verticalLayout_2.addWidget(self.function2Btn)
        self.function3Btn = QtWidgets.QPushButton(self.tab_debug)
        self.function3Btn.setObjectName("function3Btn")
        self.verticalLayout_2.addWidget(self.function3Btn)
        self.mainTab.addTab(self.tab_debug, "")
        self.gridLayout_2.addWidget(self.mainTab, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.mainTab.setCurrentIndex(0)
        self.exptPlotTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "NMR Spectrometer"))
        self.sampleTitleLbl.setText(_translate("mainWindow", "Sample Information"))
        self.sampleNameLbl.setText(_translate("mainWindow", "Sample name"))
        self.sampleMassLbl.setText(_translate("mainWindow", "Sample mass (mg)"))
        self.currentSampleNameLbl.setText(_translate("mainWindow", "Current sample name: No sample information!"))
        self.currentSampleMassLbl.setText(_translate("mainWindow", "Current sample mass: No sample information!"))
        self.confirmSampleInfoBtn.setText(_translate("mainWindow", "Confirm sample information"))
        self.clearSampleInfoBtn.setText(_translate("mainWindow", "Clear sample information"))
        self.sampleTabNextBtn.setText(_translate("mainWindow", "Next"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_sample), _translate("mainWindow", "Sample"))
        self.sequenceTitleLbl.setText(_translate("mainWindow", "Sequence"))
        self.createSeqLbl.setText(_translate("mainWindow", "Create"))
        self.frequencyLbl.setText(_translate("mainWindow", "Frequency (MHz)"))
        self.gapLenLbl.setText(_translate("mainWindow", "Gap length (ns)"))
        self.phaseLbl.setText(_translate("mainWindow", "Phase"))
        self.pulse1LenLbl.setText(_translate("mainWindow", "Pulse 1 length (ns)"))
        self.pulse2LenLbl.setText(_translate("mainWindow", "Pulse 2 length (ns)"))
        self.recLenLbl.setText(_translate("mainWindow", "Record length (ns)"))
        self.phaseComboBox.setItemText(0, _translate("mainWindow", "0"))
        self.phaseComboBox.setItemText(1, _translate("mainWindow", "90"))
        self.phaseComboBox.setItemText(2, _translate("mainWindow", "180"))
        self.phaseComboBox.setItemText(3, _translate("mainWindow", "270"))
        self.clearAllBtn.setText(_translate("mainWindow", "Clear all"))
        self.loadSeqTitleLbl.setText(_translate("mainWindow", "Load"))
        self.loadSeqBtn.setText(_translate("mainWindow", "Load"))
        self.loadedSeqLbl.setText(_translate("mainWindow", "Loaded sequence"))
        self.loadedSeqLineEdit.setPlaceholderText(_translate("mainWindow", "No sequence loaded!"))
        self.saveSeqTitleLbl.setText(_translate("mainWindow", "Save"))
        self.savedSeqLbl.setText(_translate("mainWindow", "Saved sequence"))
        self.savedSeqLineEdit.setPlaceholderText(_translate("mainWindow", "No sequence saved!"))
        self.saveSeqBtn.setText(_translate("mainWindow", "Save"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_seq), _translate("mainWindow", "Sequence"))
        self.exptTitleLbl.setText(_translate("mainWindow", "Create Experiment"))
        self.exptTreeWidget.headerItem().setText(0, _translate("mainWindow", "Type"))
        self.exptTreeWidget.headerItem().setText(1, _translate("mainWindow", "Command"))
        self.exptTreeWidget.headerItem().setText(2, _translate("mainWindow", "Repeats"))
        self.addSeqBtn.setText(_translate("mainWindow", "Add Spectrometer Command"))
        self.editSeqBtn.setText(_translate("mainWindow", "Edit Command"))
        self.removeSeqBtn.setText(_translate("mainWindow", "Remove Command"))
        self.pushButton_4.setText(_translate("mainWindow", "Add PPMS Command"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_expt), _translate("mainWindow", "Experiment"))
        self.label.setText(_translate("mainWindow", "Run Experiment"))
        self.runExptBtn.setText(_translate("mainWindow", "Run Experiment"))
        self.currentSeqLbl.setText(_translate("mainWindow", "Current command: --"))
        self.currentRepeatLbl.setText(_translate("mainWindow", "Current repeat: --"))
        self.exptPlotTabWidget.setTabText(self.exptPlotTabWidget.indexOf(self.tab_liveNMR), _translate("mainWindow", "NMR"))
        self.exptPlotTabWidget.setTabText(self.exptPlotTabWidget.indexOf(self.tab_livePPMS), _translate("mainWindow", "PPMS"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_run), _translate("mainWindow", "Run"))
        self.label_2.setText(_translate("mainWindow", "PPMS Status"))
        self.TempValDescLbl.setText(_translate("mainWindow", "Temperature (K)"))
        self.TempValLbl.setText(_translate("mainWindow", "--"))
        self.TempStateDescLbl.setText(_translate("mainWindow", "Status"))
        self.TempStateLbl.setText(_translate("mainWindow", "--"))
        self.SetTempBtn.setText(_translate("mainWindow", "Set Temperature"))
        self.FieldValDesclbl.setText(_translate("mainWindow", "Magnetic Field (Oe)"))
        self.FieldValLbl.setText(_translate("mainWindow", "--"))
        self.FieldStateLbl.setText(_translate("mainWindow", "--"))
        self.FieldStateDescLbl.setText(_translate("mainWindow", "Status"))
        self.SetFieldBtn.setText(_translate("mainWindow", "Set Field"))
        self.LevelValLbl.setText(_translate("mainWindow", "--"))
        self.LevelValDescLbl.setText(_translate("mainWindow", "Helium Level (%)"))
        self.chamberStatusDescLbl.setText(_translate("mainWindow", "Chamber Status"))
        self.chamberStatusLbl.setText(_translate("mainWindow", "--"))
        self.PPMSAutoUpdateBtn.setText(_translate("mainWindow", "Auto Update"))
        self.PPMSUpdateBtn.setText(_translate("mainWindow", "Update"))
        self.PPMSConnectBtn.setText(_translate("mainWindow", "Connect"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_PPMS), _translate("mainWindow", "PPMS"))
        self.function1Btn.setText(_translate("mainWindow", "Function 1"))
        self.function2Btn.setText(_translate("mainWindow", "Function 2"))
        self.function3Btn.setText(_translate("mainWindow", "Function 3"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_debug), _translate("mainWindow", "Debug"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

