# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.expt_tab = QtWidgets.QWidget()
        self.expt_tab.setObjectName("expt_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.expt_tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.exptTabFrame = QtWidgets.QFrame(self.expt_tab)
        self.exptTabFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.exptTabFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.exptTabFrame.setLineWidth(3)
        self.exptTabFrame.setObjectName("exptTabFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.exptTabFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftFrame = QtWidgets.QFrame(self.exptTabFrame)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.currentInfoFrame = QtWidgets.QFrame(self.leftFrame)
        self.currentInfoFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.currentInfoFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.currentInfoFrame.setLineWidth(0)
        self.currentInfoFrame.setObjectName("currentInfoFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.currentInfoFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.currentDataDir = QtWidgets.QLabel(self.currentInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentDataDir.sizePolicy().hasHeightForWidth())
        self.currentDataDir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currentDataDir.setFont(font)
        self.currentDataDir.setObjectName("currentDataDir")
        self.gridLayout_4.addWidget(self.currentDataDir, 1, 2, 1, 1)
        self.currentUserLbl = QtWidgets.QLabel(self.currentInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentUserLbl.sizePolicy().hasHeightForWidth())
        self.currentUserLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currentUserLbl.setFont(font)
        self.currentUserLbl.setObjectName("currentUserLbl")
        self.gridLayout_4.addWidget(self.currentUserLbl, 0, 0, 1, 1)
        self.currentSampleLbl = QtWidgets.QLabel(self.currentInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentSampleLbl.sizePolicy().hasHeightForWidth())
        self.currentSampleLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currentSampleLbl.setFont(font)
        self.currentSampleLbl.setObjectName("currentSampleLbl")
        self.gridLayout_4.addWidget(self.currentSampleLbl, 1, 0, 1, 1)
        self.currentSampleLineEdit = QtWidgets.QLineEdit(self.currentInfoFrame)
        self.currentSampleLineEdit.setReadOnly(True)
        self.currentSampleLineEdit.setObjectName("currentSampleLineEdit")
        self.gridLayout_4.addWidget(self.currentSampleLineEdit, 1, 1, 1, 1)
        self.currentDataDirLineEdit = QtWidgets.QLineEdit(self.currentInfoFrame)
        self.currentDataDirLineEdit.setReadOnly(True)
        self.currentDataDirLineEdit.setObjectName("currentDataDirLineEdit")
        self.gridLayout_4.addWidget(self.currentDataDirLineEdit, 1, 3, 1, 1)
        self.currentUserLineEdit = QtWidgets.QLineEdit(self.currentInfoFrame)
        self.currentUserLineEdit.setObjectName("currentUserLineEdit")
        self.gridLayout_4.addWidget(self.currentUserLineEdit, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.currentInfoFrame)
        self.frame_5 = QtWidgets.QFrame(self.leftFrame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_6.addWidget(self.lineEdit_5, 0, 4, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_6.addWidget(self.lineEdit_6, 2, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_6.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_6.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.plotFrames = QtWidgets.QFrame(self.leftFrame)
        self.plotFrames.setFrameShape(QtWidgets.QFrame.Box)
        self.plotFrames.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plotFrames.setLineWidth(0)
        self.plotFrames.setObjectName("plotFrames")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.plotFrames)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timePlotWidget = MplWidget(self.plotFrames)
        self.timePlotWidget.setObjectName("timePlotWidget")
        self.horizontalLayout_2.addWidget(self.timePlotWidget)
        self.frqPlotWidget = MplWidget(self.plotFrames)
        self.frqPlotWidget.setObjectName("frqPlotWidget")
        self.horizontalLayout_2.addWidget(self.frqPlotWidget)
        self.verticalLayout.addWidget(self.plotFrames)
        self.horizontalLayout.addWidget(self.leftFrame)
        self.rightFrame = QtWidgets.QFrame(self.exptTabFrame)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.statusFrame = QtWidgets.QFrame(self.rightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusFrame.sizePolicy().hasHeightForWidth())
        self.statusFrame.setSizePolicy(sizePolicy)
        self.statusFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.statusFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.statusFrame.setLineWidth(0)
        self.statusFrame.setObjectName("statusFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.statusFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tempValLbl = QtWidgets.QLabel(self.statusFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tempValLbl.setFont(font)
        self.tempValLbl.setScaledContents(False)
        self.tempValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.tempValLbl.setObjectName("tempValLbl")
        self.gridLayout_3.addWidget(self.tempValLbl, 0, 1, 1, 1)
        self.fieldValLbl = QtWidgets.QLabel(self.statusFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fieldValLbl.setFont(font)
        self.fieldValLbl.setScaledContents(False)
        self.fieldValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fieldValLbl.setObjectName("fieldValLbl")
        self.gridLayout_3.addWidget(self.fieldValLbl, 1, 1, 1, 1)
        self.fieldLbl = QtWidgets.QLabel(self.statusFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fieldLbl.setFont(font)
        self.fieldLbl.setScaledContents(False)
        self.fieldLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fieldLbl.setObjectName("fieldLbl")
        self.gridLayout_3.addWidget(self.fieldLbl, 1, 0, 1, 1)
        self.tempLbl = QtWidgets.QLabel(self.statusFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tempLbl.setFont(font)
        self.tempLbl.setScaledContents(False)
        self.tempLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLbl.setObjectName("tempLbl")
        self.gridLayout_3.addWidget(self.tempLbl, 0, 0, 1, 1)
        self.currentRepeatLbl = QtWidgets.QLabel(self.statusFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currentRepeatLbl.setFont(font)
        self.currentRepeatLbl.setScaledContents(False)
        self.currentRepeatLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.currentRepeatLbl.setObjectName("currentRepeatLbl")
        self.gridLayout_3.addWidget(self.currentRepeatLbl, 2, 0, 1, 1)
        self.repeatValLbl = QtWidgets.QLabel(self.statusFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repeatValLbl.setFont(font)
        self.repeatValLbl.setScaledContents(False)
        self.repeatValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.repeatValLbl.setObjectName("repeatValLbl")
        self.gridLayout_3.addWidget(self.repeatValLbl, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.statusFrame)
        self.treeWidgetFrame = QtWidgets.QFrame(self.rightFrame)
        self.treeWidgetFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidgetFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeWidgetFrame.setLineWidth(0)
        self.treeWidgetFrame.setObjectName("treeWidgetFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.treeWidgetFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.exptTreeWidget = QtWidgets.QTreeWidget(self.treeWidgetFrame)
        self.exptTreeWidget.setObjectName("exptTreeWidget")
        self.verticalLayout_3.addWidget(self.exptTreeWidget)
        self.verticalLayout_2.addWidget(self.treeWidgetFrame)
        self.buttonFrame = QtWidgets.QFrame(self.rightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonFrame.sizePolicy().hasHeightForWidth())
        self.buttonFrame.setSizePolicy(sizePolicy)
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.buttonFrame.setLineWidth(0)
        self.buttonFrame.setObjectName("buttonFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.buttonFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.addNMRCommandBtn = QtWidgets.QPushButton(self.buttonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNMRCommandBtn.sizePolicy().hasHeightForWidth())
        self.addNMRCommandBtn.setSizePolicy(sizePolicy)
        self.addNMRCommandBtn.setObjectName("addNMRCommandBtn")
        self.gridLayout_5.addWidget(self.addNMRCommandBtn, 0, 0, 1, 1)
        self.removeCommandBtn = QtWidgets.QPushButton(self.buttonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeCommandBtn.sizePolicy().hasHeightForWidth())
        self.removeCommandBtn.setSizePolicy(sizePolicy)
        self.removeCommandBtn.setObjectName("removeCommandBtn")
        self.gridLayout_5.addWidget(self.removeCommandBtn, 3, 0, 1, 1)
        self.addPPMSCommandBtn = QtWidgets.QPushButton(self.buttonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPPMSCommandBtn.sizePolicy().hasHeightForWidth())
        self.addPPMSCommandBtn.setSizePolicy(sizePolicy)
        self.addPPMSCommandBtn.setObjectName("addPPMSCommandBtn")
        self.gridLayout_5.addWidget(self.addPPMSCommandBtn, 1, 0, 1, 1)
        self.startExptBtn = QtWidgets.QPushButton(self.buttonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startExptBtn.sizePolicy().hasHeightForWidth())
        self.startExptBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startExptBtn.setFont(font)
        self.startExptBtn.setObjectName("startExptBtn")
        self.gridLayout_5.addWidget(self.startExptBtn, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 4, 0, 1, 1)
        self.editCommandBtn = QtWidgets.QPushButton(self.buttonFrame)
        self.editCommandBtn.setObjectName("editCommandBtn")
        self.gridLayout_5.addWidget(self.editCommandBtn, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.buttonFrame)
        self.horizontalLayout.addWidget(self.rightFrame)
        self.gridLayout_2.addWidget(self.exptTabFrame, 2, 0, 1, 1)
        self.mainTabWidget.addTab(self.expt_tab, "")
        self.seq_tab = QtWidgets.QWidget()
        self.seq_tab.setObjectName("seq_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.seq_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.seq_tab)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.sequenceTitleFrame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceTitleFrame.sizePolicy().hasHeightForWidth())
        self.sequenceTitleFrame.setSizePolicy(sizePolicy)
        self.sequenceTitleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sequenceTitleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sequenceTitleFrame.setObjectName("sequenceTitleFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.sequenceTitleFrame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.sequenceTitleLbl = QtWidgets.QLabel(self.sequenceTitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceTitleLbl.sizePolicy().hasHeightForWidth())
        self.sequenceTitleLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sequenceTitleLbl.setFont(font)
        self.sequenceTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sequenceTitleLbl.setObjectName("sequenceTitleLbl")
        self.verticalLayout_11.addWidget(self.sequenceTitleLbl)
        self.sequenceHLine = QtWidgets.QFrame(self.sequenceTitleFrame)
        self.sequenceHLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sequenceHLine.setLineWidth(3)
        self.sequenceHLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.sequenceHLine.setObjectName("sequenceHLine")
        self.verticalLayout_11.addWidget(self.sequenceHLine)
        self.gridLayout_8.addWidget(self.sequenceTitleFrame, 0, 0, 1, 2)
        self.createSequenceFrame = QtWidgets.QFrame(self.frame)
        self.createSequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createSequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createSequenceFrame.setObjectName("createSequenceFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.createSequenceFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.createSeqLbl = QtWidgets.QLabel(self.createSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createSeqLbl.sizePolicy().hasHeightForWidth())
        self.createSeqLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.createSeqLbl.setFont(font)
        self.createSeqLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.createSeqLbl.setObjectName("createSeqLbl")
        self.verticalLayout_12.addWidget(self.createSeqLbl)
        self.createSequenceLineEditFrame = QtWidgets.QFrame(self.createSequenceFrame)
        self.createSequenceLineEditFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createSequenceLineEditFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createSequenceLineEditFrame.setObjectName("createSequenceLineEditFrame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.createSequenceLineEditFrame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frequencyLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequencyLbl.sizePolicy().hasHeightForWidth())
        self.frequencyLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frequencyLbl.setFont(font)
        self.frequencyLbl.setObjectName("frequencyLbl")
        self.gridLayout_12.addWidget(self.frequencyLbl, 0, 0, 1, 1)
        self.pulse2LenLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse2LenLineEdit.sizePolicy().hasHeightForWidth())
        self.pulse2LenLineEdit.setSizePolicy(sizePolicy)
        self.pulse2LenLineEdit.setObjectName("pulse2LenLineEdit")
        self.gridLayout_12.addWidget(self.pulse2LenLineEdit, 3, 1, 1, 1)
        self.gapLenLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gapLenLbl.sizePolicy().hasHeightForWidth())
        self.gapLenLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gapLenLbl.setFont(font)
        self.gapLenLbl.setObjectName("gapLenLbl")
        self.gridLayout_12.addWidget(self.gapLenLbl, 4, 0, 1, 1)
        self.gapLenLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gapLenLineEdit.sizePolicy().hasHeightForWidth())
        self.gapLenLineEdit.setSizePolicy(sizePolicy)
        self.gapLenLineEdit.setObjectName("gapLenLineEdit")
        self.gridLayout_12.addWidget(self.gapLenLineEdit, 4, 1, 1, 1)
        self.phaseLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseLbl.sizePolicy().hasHeightForWidth())
        self.phaseLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phaseLbl.setFont(font)
        self.phaseLbl.setObjectName("phaseLbl")
        self.gridLayout_12.addWidget(self.phaseLbl, 1, 0, 1, 1)
        self.pulse1LenLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse1LenLbl.sizePolicy().hasHeightForWidth())
        self.pulse1LenLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pulse1LenLbl.setFont(font)
        self.pulse1LenLbl.setObjectName("pulse1LenLbl")
        self.gridLayout_12.addWidget(self.pulse1LenLbl, 2, 0, 1, 1)
        self.pulse1LenLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse1LenLineEdit.sizePolicy().hasHeightForWidth())
        self.pulse1LenLineEdit.setSizePolicy(sizePolicy)
        self.pulse1LenLineEdit.setObjectName("pulse1LenLineEdit")
        self.gridLayout_12.addWidget(self.pulse1LenLineEdit, 2, 1, 1, 1)
        self.frequencyLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequencyLineEdit.sizePolicy().hasHeightForWidth())
        self.frequencyLineEdit.setSizePolicy(sizePolicy)
        self.frequencyLineEdit.setObjectName("frequencyLineEdit")
        self.gridLayout_12.addWidget(self.frequencyLineEdit, 0, 1, 1, 1)
        self.pulse2LenLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse2LenLbl.sizePolicy().hasHeightForWidth())
        self.pulse2LenLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pulse2LenLbl.setFont(font)
        self.pulse2LenLbl.setObjectName("pulse2LenLbl")
        self.gridLayout_12.addWidget(self.pulse2LenLbl, 3, 0, 1, 1)
        self.recLenLbl = QtWidgets.QLabel(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recLenLbl.sizePolicy().hasHeightForWidth())
        self.recLenLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.recLenLbl.setFont(font)
        self.recLenLbl.setObjectName("recLenLbl")
        self.gridLayout_12.addWidget(self.recLenLbl, 5, 0, 1, 1)
        self.recLenLineEdit = QtWidgets.QLineEdit(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recLenLineEdit.sizePolicy().hasHeightForWidth())
        self.recLenLineEdit.setSizePolicy(sizePolicy)
        self.recLenLineEdit.setObjectName("recLenLineEdit")
        self.gridLayout_12.addWidget(self.recLenLineEdit, 5, 1, 1, 1)
        self.phaseComboBox = QtWidgets.QComboBox(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseComboBox.sizePolicy().hasHeightForWidth())
        self.phaseComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phaseComboBox.setFont(font)
        self.phaseComboBox.setFrame(True)
        self.phaseComboBox.setObjectName("phaseComboBox")
        self.phaseComboBox.addItem("")
        self.phaseComboBox.addItem("")
        self.phaseComboBox.addItem("")
        self.phaseComboBox.addItem("")
        self.gridLayout_12.addWidget(self.phaseComboBox, 1, 1, 1, 1)
        self.clearAllBtn = QtWidgets.QPushButton(self.createSequenceLineEditFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearAllBtn.sizePolicy().hasHeightForWidth())
        self.clearAllBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearAllBtn.setFont(font)
        self.clearAllBtn.setObjectName("clearAllBtn")
        self.gridLayout_12.addWidget(self.clearAllBtn, 6, 1, 1, 1)
        self.verticalLayout_12.addWidget(self.createSequenceLineEditFrame)
        self.gridLayout_8.addWidget(self.createSequenceFrame, 1, 0, 1, 1)
        self.loadAndSaveSequenceFrame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadAndSaveSequenceFrame.sizePolicy().hasHeightForWidth())
        self.loadAndSaveSequenceFrame.setSizePolicy(sizePolicy)
        self.loadAndSaveSequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadAndSaveSequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadAndSaveSequenceFrame.setObjectName("loadAndSaveSequenceFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.loadAndSaveSequenceFrame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.loadSeqTitleLbl = QtWidgets.QLabel(self.loadAndSaveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSeqTitleLbl.sizePolicy().hasHeightForWidth())
        self.loadSeqTitleLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.loadSeqTitleLbl.setFont(font)
        self.loadSeqTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.loadSeqTitleLbl.setObjectName("loadSeqTitleLbl")
        self.verticalLayout_13.addWidget(self.loadSeqTitleLbl)
        self.loadSequenceFrame = QtWidgets.QFrame(self.loadAndSaveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSequenceFrame.sizePolicy().hasHeightForWidth())
        self.loadSequenceFrame.setSizePolicy(sizePolicy)
        self.loadSequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadSequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadSequenceFrame.setObjectName("loadSequenceFrame")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.loadSequenceFrame)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.loadSeqBtn = QtWidgets.QPushButton(self.loadSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSeqBtn.sizePolicy().hasHeightForWidth())
        self.loadSeqBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadSeqBtn.setFont(font)
        self.loadSeqBtn.setObjectName("loadSeqBtn")
        self.gridLayout_17.addWidget(self.loadSeqBtn, 2, 1, 1, 1)
        self.loadedSeqLbl = QtWidgets.QLabel(self.loadSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadedSeqLbl.sizePolicy().hasHeightForWidth())
        self.loadedSeqLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadedSeqLbl.setFont(font)
        self.loadedSeqLbl.setObjectName("loadedSeqLbl")
        self.gridLayout_17.addWidget(self.loadedSeqLbl, 0, 0, 1, 1)
        self.loadedSeqLineEdit = QtWidgets.QLineEdit(self.loadSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadedSeqLineEdit.sizePolicy().hasHeightForWidth())
        self.loadedSeqLineEdit.setSizePolicy(sizePolicy)
        self.loadedSeqLineEdit.setText("")
        self.loadedSeqLineEdit.setReadOnly(True)
        self.loadedSeqLineEdit.setObjectName("loadedSeqLineEdit")
        self.gridLayout_17.addWidget(self.loadedSeqLineEdit, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.loadSequenceFrame)
        self.saveSeqTitleLbl = QtWidgets.QLabel(self.loadAndSaveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSeqTitleLbl.sizePolicy().hasHeightForWidth())
        self.saveSeqTitleLbl.setSizePolicy(sizePolicy)
        self.saveSeqTitleLbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.saveSeqTitleLbl.setFont(font)
        self.saveSeqTitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.saveSeqTitleLbl.setObjectName("saveSeqTitleLbl")
        self.verticalLayout_13.addWidget(self.saveSeqTitleLbl)
        self.saveSequenceFrame = QtWidgets.QFrame(self.loadAndSaveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSequenceFrame.sizePolicy().hasHeightForWidth())
        self.saveSequenceFrame.setSizePolicy(sizePolicy)
        self.saveSequenceFrame.setMinimumSize(QtCore.QSize(0, 177))
        self.saveSequenceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saveSequenceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saveSequenceFrame.setObjectName("saveSequenceFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.saveSequenceFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.savedSeqLbl = QtWidgets.QLabel(self.saveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedSeqLbl.sizePolicy().hasHeightForWidth())
        self.savedSeqLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.savedSeqLbl.setFont(font)
        self.savedSeqLbl.setObjectName("savedSeqLbl")
        self.gridLayout_7.addWidget(self.savedSeqLbl, 0, 0, 1, 1)
        self.savedSeqLineEdit = QtWidgets.QLineEdit(self.saveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedSeqLineEdit.sizePolicy().hasHeightForWidth())
        self.savedSeqLineEdit.setSizePolicy(sizePolicy)
        self.savedSeqLineEdit.setReadOnly(True)
        self.savedSeqLineEdit.setObjectName("savedSeqLineEdit")
        self.gridLayout_7.addWidget(self.savedSeqLineEdit, 0, 1, 1, 1)
        self.saveSeqBtn = QtWidgets.QPushButton(self.saveSequenceFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSeqBtn.sizePolicy().hasHeightForWidth())
        self.saveSeqBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveSeqBtn.setFont(font)
        self.saveSeqBtn.setObjectName("saveSeqBtn")
        self.gridLayout_7.addWidget(self.saveSeqBtn, 1, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.saveSequenceFrame)
        self.gridLayout_8.addWidget(self.loadAndSaveSequenceFrame, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.mainTabWidget.addTab(self.seq_tab, "")
        self.gridLayout.addWidget(self.mainTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.currentDataDir.setText(_translate("MainWindow", "Current data directory"))
        self.currentUserLbl.setText(_translate("MainWindow", "Current User"))
        self.currentSampleLbl.setText(_translate("MainWindow", "Current Sample"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.tempValLbl.setText(_translate("MainWindow", "--"))
        self.fieldValLbl.setText(_translate("MainWindow", "--"))
        self.fieldLbl.setText(_translate("MainWindow", "Magnetic Field (Oe)"))
        self.tempLbl.setText(_translate("MainWindow", "Temperature (K)"))
        self.currentRepeatLbl.setText(_translate("MainWindow", "Repeat number"))
        self.repeatValLbl.setText(_translate("MainWindow", "--"))
        self.exptTreeWidget.headerItem().setText(0, _translate("MainWindow", "Type"))
        self.exptTreeWidget.headerItem().setText(1, _translate("MainWindow", "Command"))
        self.exptTreeWidget.headerItem().setText(2, _translate("MainWindow", "Repeats"))
        self.addNMRCommandBtn.setText(_translate("MainWindow", "Add NMR command"))
        self.removeCommandBtn.setText(_translate("MainWindow", "Remove command"))
        self.addPPMSCommandBtn.setText(_translate("MainWindow", "Add PPMS command"))
        self.startExptBtn.setText(_translate("MainWindow", "Start experiment"))
        self.editCommandBtn.setText(_translate("MainWindow", "Edit command"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.expt_tab), _translate("MainWindow", "Experiment"))
        self.sequenceTitleLbl.setText(_translate("MainWindow", "Sequence"))
        self.createSeqLbl.setText(_translate("MainWindow", "Create"))
        self.frequencyLbl.setText(_translate("MainWindow", "Frequency (MHz)"))
        self.gapLenLbl.setText(_translate("MainWindow", "Gap length (ns)"))
        self.phaseLbl.setText(_translate("MainWindow", "Phase"))
        self.pulse1LenLbl.setText(_translate("MainWindow", "Pulse 1 length (ns)"))
        self.pulse2LenLbl.setText(_translate("MainWindow", "Pulse 2 length (ns)"))
        self.recLenLbl.setText(_translate("MainWindow", "Record length (ns)"))
        self.phaseComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.phaseComboBox.setItemText(1, _translate("MainWindow", "90"))
        self.phaseComboBox.setItemText(2, _translate("MainWindow", "180"))
        self.phaseComboBox.setItemText(3, _translate("MainWindow", "270"))
        self.clearAllBtn.setText(_translate("MainWindow", "Clear all"))
        self.loadSeqTitleLbl.setText(_translate("MainWindow", "Load"))
        self.loadSeqBtn.setText(_translate("MainWindow", "Load"))
        self.loadedSeqLbl.setText(_translate("MainWindow", "Loaded sequence"))
        self.loadedSeqLineEdit.setPlaceholderText(_translate("MainWindow", "No sequence loaded!"))
        self.saveSeqTitleLbl.setText(_translate("MainWindow", "Save"))
        self.savedSeqLbl.setText(_translate("MainWindow", "Saved sequence"))
        self.savedSeqLineEdit.setPlaceholderText(_translate("MainWindow", "No sequence saved!"))
        self.saveSeqBtn.setText(_translate("MainWindow", "Save"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.seq_tab), _translate("MainWindow", "Sequence"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

